# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0002_flag_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='stores',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for these stores.', to='store.Store'),
        ),
    ]
