# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0002_auto_20161201_0958'),
        ('waffle', '0003_auto_20170921_1306'),
    ]

    operations = [
    ]
