# Generated by Django 2.1.8 on 2019-08-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0004_merge_20180312_1211'),
        ('waffle', '0003_update_strings_for_i18n'),
    ]

    operations = [
    ]
